//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCrimeReportingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crime
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public System.DateTime CrimeDate { get; set; }
        public string Name { get; set; }
        public string CriminalName { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Location { get; set; }
        public string Files { get; set; }
        public bool Status { get; set; }
        public System.DateTime ReportingDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
